### ISSUE TITLE
Make Vinyl Cutter operational

### ISSUE THREAD

**Issue by Ilidur** [EOF-Hackspace/Operations#2]
One potential member depends on the vinyl cutter to do their work. Below is the breakdown of what needs to happen before we declare it operational.

- [ ] Find a space for the vinyl cutter to sit so that it may be operated safely (can be on its stand). [#3]
- [ ] Install software on the space's Windows machine [#4]
- [ ] Do test cut
- [ ] Make accessible a safety sheet/risk assessment [#5]
- [ ] Have a short introduction document on getting a cut done [#6]
